sudo: required

language: java
jdk: openjdk8

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - chmod +x gradlew

before_cache:
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  - $HOME/.gradle/caches/modules-2
  - $HOME/.gradle/wrapper/

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
  - /home/travis/build/CodeBrig/GitSocratic/build/distributions/gitsocratic-0.2.tar
  - /home/travis/build/CodeBrig/GitSocratic/build/distributions/gitsocratic-0.2.zip
  skip_cleanup: true
  on:
    tags: true
