match
{($function) isa DECLARATION_FUNCTION;}
or
{($function) isa DECLARATION_FUNCTION_VISIBILITY_WORLD;};
(is_parent: $function, is_child: $functionName);
($functionName) isa FUNCTION;
($functionName) isa NAME;
($functionName) isa IDENTIFIER;
$functionName has token "<name>";
aggregate count $function;