match
$function isa <language>SourceArtifact;
($function) isa DECLARATION;
($function) isa FUNCTION;
not {
	($function) isa ARGUMENT;
};
not {
	($function) isa RETURN;
};
not {
	($function) isa INCOMPLETE;
};
not {
	($function) isa BODY;
};
get $function; count;