match
$function isa SourceArtifact;
($function) isa DECLARATION;
($function) isa FUNCTION;
not {
	($function) isa ARGUMENT;
};
not {
	($function) isa RETURN;
};
not {
	($function) isa INCOMPLETE;
};
not {
	($function) isa BODY;
};

{
    #self-identified functions
    ($function) isa IDENTIFIER;
    $function has token "<name>";
} or {
    #child-node-identified functions
    (is_parent: $function, is_child: $functionName);
    ($functionName) isa IDENTIFIER;
    $functionName has token "<name>";
};

get $function; count;